CREATE TABLE IF NOT EXISTS job (
    job_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE IF NOT EXISTS address (
    address_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE IF NOT EXISTS mogak_category (
    mogak_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS period (
    period_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    days varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_id integer,
    job_id integer,
    age integer,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    email varchar(255),
    gender char(1),
    nickname varchar(255),
    profile_img_name varchar(255),
    profile_img_url varchar(255),
    refresh_token varchar(512),
    role varchar(255),
    CONSTRAINT fk_users_address FOREIGN KEY (address_id) REFERENCES address (address_id),
    CONSTRAINT fk_users_job FOREIGN KEY (job_id) REFERENCES job (job_id)
);

CREATE TABLE IF NOT EXISTS user_agree (
    agree_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    optional_agree boolean NOT NULL,
    require_agree boolean NOT NULL,
    CONSTRAINT fk_user_agree_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS social_account (
    social_account_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6),
    email varchar(255),
    provider varchar(20) NOT NULL,
    provider_user_id varchar(255) NOT NULL,
    CONSTRAINT fk_social_account_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uq_social_account_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_social_account_user_provider UNIQUE (user_id, provider)
);

CREATE TABLE IF NOT EXISTS modarat (
    modarat_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    color varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    CONSTRAINT fk_modarat_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS follow (
    follow_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id bigint,
    to_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_follow_from_user FOREIGN KEY (from_id) REFERENCES users (user_id),
    CONSTRAINT fk_follow_to_user FOREIGN KEY (to_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS user_follow (
    follow_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id bigint,
    to_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_user_follow_from_user FOREIGN KEY (from_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_follow_to_user FOREIGN KEY (to_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS mogak (
    mogak_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    big_category integer,
    modarat_id bigint,
    user_id bigint,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    color varchar(255),
    small_category varchar(255),
    title varchar(255) NOT NULL,
    CONSTRAINT fk_mogak_category FOREIGN KEY (big_category) REFERENCES mogak_category (mogak_category_id),
    CONSTRAINT fk_mogak_modarat FOREIGN KEY (modarat_id) REFERENCES modarat (modarat_id),
    CONSTRAINT fk_mogak_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS jogak (
    jogak_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mogak_category integer,
    mogak_id bigint,
    user_id bigint,
    achievement integer,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    end_at date,
    is_routine boolean NOT NULL,
    start_at date NOT NULL,
    state varchar(255),
    title varchar(255) NOT NULL,
    CONSTRAINT fk_jogak_category FOREIGN KEY (mogak_category) REFERENCES mogak_category (mogak_category_id),
    CONSTRAINT fk_jogak_mogak FOREIGN KEY (mogak_id) REFERENCES mogak (mogak_id),
    CONSTRAINT fk_jogak_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS jogak_period (
    jogak_period_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jogak_id bigint,
    period_id integer,
    CONSTRAINT fk_jogak_period_jogak FOREIGN KEY (jogak_id) REFERENCES jogak (jogak_id),
    CONSTRAINT fk_jogak_period_period FOREIGN KEY (period_id) REFERENCES period (period_id)
);

CREATE TABLE IF NOT EXISTS daily_jogak (
    daily_jogak_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jogak_id bigint,
    mogak_category integer,
    mogak_id bigint,
    created_at timestamp(6),
    deleted_at timestamp(6),
    target_date date NOT NULL,
    updated_at timestamp(6),
    is_routine boolean NOT NULL,
    status varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    CONSTRAINT fk_daily_jogak_jogak FOREIGN KEY (jogak_id) REFERENCES jogak (jogak_id),
    CONSTRAINT fk_daily_jogak_category FOREIGN KEY (mogak_category) REFERENCES mogak_category (mogak_category_id),
    CONSTRAINT fk_daily_jogak_mogak FOREIGN KEY (mogak_id) REFERENCES mogak (mogak_id)
);

CREATE TABLE IF NOT EXISTS post (
    post_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_jogak_id bigint NOT NULL,
    user_id bigint,
    comment_cnt integer NOT NULL,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    like_cnt integer NOT NULL,
    post_thumbnail_url varchar(255) NOT NULL,
    contents varchar(350) NOT NULL,
    view_cnt integer NOT NULL,
    CONSTRAINT fk_post_daily_jogak FOREIGN KEY (daily_jogak_id) REFERENCES daily_jogak (daily_jogak_id),
    CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS post_comment (
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint,
    user_id bigint,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    contents varchar(255) NOT NULL,
    CONSTRAINT fk_post_comment_post FOREIGN KEY (post_id) REFERENCES post (post_id),
    CONSTRAINT fk_post_comment_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS post_img (
    post_img_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    img_name varchar(255) NOT NULL,
    img_url varchar(255) NOT NULL,
    CONSTRAINT fk_post_img_post FOREIGN KEY (post_id) REFERENCES post (post_id)
);

CREATE TABLE IF NOT EXISTS post_like (
    like_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint,
    user_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_post_like_post FOREIGN KEY (post_id) REFERENCES post (post_id),
    CONSTRAINT fk_post_like_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS notice (
    notice_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    content varchar(255) NOT NULL,
    title varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS notice_img (
    notice_img_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    img_url varchar(255) NOT NULL,
    CONSTRAINT fk_notice_img_notice FOREIGN KEY (notice_id) REFERENCES notice (notice_id)
);

CREATE TABLE IF NOT EXISTS report (
    report_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id bigint,
    to_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    category varchar(255) NOT NULL,
    state varchar(255) NOT NULL,
    CONSTRAINT fk_report_from_user FOREIGN KEY (from_id) REFERENCES users (user_id),
    CONSTRAINT fk_report_to_user FOREIGN KEY (to_id) REFERENCES users (user_id)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_nickname ON users (nickname);
CREATE UNIQUE INDEX IF NOT EXISTS idx_job_name ON job (name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_address_name ON address (name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mogak_category_name ON mogak_category (name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_period_days ON period (days);
CREATE INDEX IF NOT EXISTS idx_mogak_modarat_id ON mogak (modarat_id);
CREATE INDEX IF NOT EXISTS idx_jogak_mogak_id ON jogak (mogak_id);
CREATE INDEX IF NOT EXISTS idx_daily_jogak_jogak_id ON daily_jogak (jogak_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_daily_jogak_jogak_target_date ON daily_jogak (jogak_id, target_date) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_post_daily_jogak_id ON post (daily_jogak_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_post_active_daily_jogak ON post (daily_jogak_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_post_like_post_user ON post_like (post_id, user_id);
